export const MenuConstant = [
  {
    id: 0,
    order: 0,
    label: "Store",
    url: "",
    menuSubgroup: [
      {
        id: 0,
        subheader: "Shop",
        order: 0,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Shop The Latest",
            url: "",
            order: 0,
            isCustomizedText: true,
          },
          {
            id: 1,
            subMenuLabel: "Mac",
            url: "",
            order: 1,
            isCustomizedText: true,
          },
          {
            id: 2,
            subMenuLabel: "iPad",
            url: "",
            order: 2,
            isCustomizedText: true,
          },
          {
            id: 3,
            subMenuLabel: "iPhone",
            url: "",
            order: 3,
            isCustomizedText: true,
          },
          {
            id: 4,
            subMenuLabel: "Apple Watch",
            url: "",
            order: 4,
            isCustomizedText: true,
          },
          {
            id: 5,
            subMenuLabel: "Accessories",
            url: "",
            order: 5,
            isCustomizedText: true,
          },
        ],
      },
      {
        id: 1,
        subheader: "Quick Links",
        order: 1,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Find a Store",
            url: "",
            order: 0,
            isCustomizedText: false,
          },
          {
            id: 1,
            subMenuLabel: "Order Status",
            url: "",
            order: 1,
            isCustomizedText: false,
          },
          {
            id: 2,
            subMenuLabel: "Apple Trade In",
            url: "",
            order: 2,
            isCustomizedText: false,
          },
          {
            id: 3,
            subMenuLabel: "Financing",
            url: "",
            order: 3,
            isCustomizedText: false,
          },
          {
            id: 4,
            subMenuLabel: "University Student Offer",
            url: "",
            order: 4,
            isCustomizedText: false,
          },
        ],
      },
      {
        id: 2,
        subheader: "Shop Special Stores",
        order: 2,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Certified Refurbished",
            url: "",
            order: 0,
            isCustomizedText: false,
          },
          {
            id: 1,
            subMenuLabel: "Education",
            url: "",
            order: 1,
            isCustomizedText: false,
          },
          {
            id: 2,
            subMenuLabel: "Business",
            url: "",
            order: 2,
            isCustomizedText: false,
          },
        ],
      },
    ],
  },
  {
    id: 1,
    order: 1,
    label: "Mac",
    url: "",
    menuSubgroup: [
      {
        id: 0,
        subheader: "Explore Mac",
        order: 0,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Explore All Mac",
            url: "",
            order: 0,
            isCustomizedText: true,
          },
          {
            id: 1,
            subMenuLabel: "Macbook Air",
            url: "",
            order: 1,
            isCustomizedText: true,
          },
          {
            id: 2,
            subMenuLabel: "Macbook Pro",
            url: "",
            order: 2,
            isCustomizedText: true,
          },
          {
            id: 3,
            subMenuLabel: "iMac",
            url: "",
            order: 3,
            isCustomizedText: true,
          },
          {
            id: 4,
            subMenuLabel: "Mac mini",
            url: "",
            order: 4,
            isCustomizedText: true,
          },
          {
            id: 5,
            subMenuLabel: "Mac Studio",
            url: "",
            order: 5,
            isCustomizedText: true,
          },
          {
            id: 6,
            subMenuLabel: "Mac Pro",
            url: "",
            order: 6,
            isCustomizedText: true,
          },
          {
            id: 7,
            subMenuLabel: "Displays",
            url: "",
            order: 7,
            isCustomizedText: true,
          },
          {
            id: 8,
            subMenuLabel: "Compare Mac",
            url: "",
            order: 8,
            isCustomizedText: false,
          },
          {
            id: 9,
            subMenuLabel: "Mac Does That",
            url: "",
            order: 9,
            isCustomizedText: false,
          },
        ],
      },
      {
        id: 1,
        subheader: "Shop Mac",
        order: 1,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Shop Mac",
            url: "",
            order: 0,
            isCustomizedText: false,
          },
          {
            id: 1,
            subMenuLabel: "Mac Accessories",
            url: "",
            order: 1,
            isCustomizedText: false,
          },
          {
            id: 2,
            subMenuLabel: "Apple Trade In",
            url: "",
            order: 2,
            isCustomizedText: false,
          },
          {
            id: 3,
            subMenuLabel: "Financing",
            url: "",
            order: 3,
            isCustomizedText: false,
          },
          {
            id: 4,
            subMenuLabel: "University Student Offer",
            url: "",
            order: 4,
            isCustomizedText: false,
          },
        ],
      },
      {
        id: 2,
        subheader: "More from Mac",
        order: 2,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Mac Support",
            url: "",
            order: 0,
            isCustomizedText: false,
          },
          {
            id: 1,
            subMenuLabel: "macOS Sonoma Preview",
            url: "",
            order: 1,
            isCustomizedText: false,
          },
          {
            id: 2,
            subMenuLabel: "Final Cut Pro",
            url: "",
            order: 2,
            isCustomizedText: false,
          },
          {
            id: 3,
            subMenuLabel: "Logic Pro",
            url: "",
            order: 3,
            isCustomizedText: false,
          },
          {
            id: 4,
            subMenuLabel: "Continuity",
            url: "",
            order: 4,
            isCustomizedText: false,
          },
          {
            id: 5,
            subMenuLabel: "iCloud",
            url: "",
            order: 5,
            isCustomizedText: false,
          },
          {
            id: 6,
            subMenuLabel: "Mac for Business",
            url: "",
            order: 6,
            isCustomizedText: false,
          },
          {
            id: 7,
            subMenuLabel: "Education",
            url: "",
            order: 7,
            isCustomizedText: false,
          },
        ],
      },
    ],
  },
  {
    id: 2,
    order: 2,
    label: "iPad",
    url: "",
    menuSubgroup: [
      {
        id: 0,
        subheader: "Explore iPad",
        order: 0,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Explore All iPad",
            url: "",
            order: 0,
            isCustomizedText: true,
          },
          {
            id: 1,
            subMenuLabel: "iPad Pro",
            url: "",
            order: 1,
            isCustomizedText: true,
          },
          {
            id: 2,
            subMenuLabel: "iPad Air",
            url: "",
            order: 2,
            isCustomizedText: true,
          },
          {
            id: 3,
            subMenuLabel: "iPad",
            url: "",
            order: 3,
            isCustomizedText: true,
          },
          {
            id: 4,
            subMenuLabel: "iPad mini",
            url: "",
            order: 4,
            isCustomizedText: true,
          },
          {
            id: 5,
            subMenuLabel: "Apple Pencil",
            url: "",
            order: 5,
            isCustomizedText: true,
          },
          {
            id: 6,
            subMenuLabel: "Keyboards",
            url: "",
            order: 6,
            isCustomizedText: true,
          },
          {
            id: 7,
            subMenuLabel: "Compare iPad",
            url: "",
            order: 7,
            isCustomizedText: false,
          },
          {
            id: 8,
            subMenuLabel: "Why iPad",
            url: "",
            order: 8,
            isCustomizedText: false,
          },
        ],
      },
      {
        id: 1,
        subheader: "Shop iPad",
        order: 1,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Shop iPad",
            url: "",
            order: 0,
            isCustomizedText: false,
          },
          {
            id: 1,
            subMenuLabel: "iPad Accessories",
            url: "",
            order: 1,
            isCustomizedText: false,
          },
          {
            id: 2,
            subMenuLabel: "Apple Trade In",
            url: "",
            order: 2,
            isCustomizedText: false,
          },
          {
            id: 3,
            subMenuLabel: "Financing",
            url: "",
            order: 3,
            isCustomizedText: false,
          },
          {
            id: 4,
            subMenuLabel: "University Student Offer",
            url: "",
            order: 4,
            isCustomizedText: false,
          },
        ],
      },
      {
        id: 2,
        subheader: "More from iPad",
        order: 2,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "iPad Support",
            url: "",
            order: 0,
            isCustomizedText: false,
          },
          {
            id: 1,
            subMenuLabel: "iPadOS 17 Preview",
            url: "",
            order: 1,
            isCustomizedText: false,
          },
          {
            id: 2,
            subMenuLabel: "Final Cut Pro for iPad",
            url: "",
            order: 2,
            isCustomizedText: false,
          },
          {
            id: 3,
            subMenuLabel: "Logic Pro for iPad",
            url: "",
            order: 3,
            isCustomizedText: false,
          },
          {
            id: 4,
            subMenuLabel: "iCloud",
            url: "",
            order: 4,
            isCustomizedText: false,
          },
          {
            id: 5,
            subMenuLabel: "Education",
            url: "",
            order: 5,
            isCustomizedText: false,
          },
        ],
      },
    ],
  },
  {
    id: 3,
    order: 3,
    label: "iPhone",
    url: "",
    menuSubgroup: [
      {
        id: 0,
        subheader: "Explore iPhone",
        order: 0,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Explore All iPhone",
            url: "",
            order: 0,
            isCustomizedText: true,
          },
          {
            id: 1,
            subMenuLabel: "iPhone 14 Pro",
            url: "",
            order: 1,
            isCustomizedText: true,
          },
          {
            id: 2,
            subMenuLabel: "iPhone 14",
            url: "",
            order: 2,
            isCustomizedText: true,
          },
          {
            id: 3,
            subMenuLabel: "iPhone 13",
            url: "",
            order: 3,
            isCustomizedText: true,
          },
          {
            id: 4,
            subMenuLabel: "iPhone 12",
            url: "",
            order: 4,
            isCustomizedText: true,
          },
          {
            id: 5,
            subMenuLabel: "iPhone SE",
            url: "",
            order: 5,
            isCustomizedText: true,
          },
          {
            id: 6,
            subMenuLabel: "Compare iPhone",
            url: "",
            order: 6,
            isCustomizedText: false,
          },
          {
            id: 7,
            subMenuLabel: "Switch from Android",
            url: "",
            order: 7,
            isCustomizedText: false,
          },
        ],
      },
      {
        id: 1,
        subheader: "Shop iPhone",
        order: 1,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Shop iPhone",
            url: "",
            order: 0,
            isCustomizedText: false,
          },
          {
            id: 1,
            subMenuLabel: "iPhone Accessories",
            url: "",
            order: 1,
            isCustomizedText: false,
          },
          {
            id: 2,
            subMenuLabel: "Apple Trade In",
            url: "",
            order: 2,
            isCustomizedText: false,
          },
          {
            id: 3,
            subMenuLabel: "Financing",
            url: "",
            order: 3,
            isCustomizedText: false,
          },
        ],
      },
      {
        id: 2,
        subheader: "More from iPhone",
        order: 2,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "iPhone Support",
            url: "",
            order: 0,
            isCustomizedText: false,
          },
          {
            id: 1,
            subMenuLabel: "iOS 17 Preview",
            url: "",
            order: 1,
            isCustomizedText: false,
          },
          {
            id: 2,
            subMenuLabel: "iPhone Privacy",
            url: "",
            order: 2,
            isCustomizedText: false,
          },
          {
            id: 3,
            subMenuLabel: "iCloud",
            url: "",
            order: 3,
            isCustomizedText: false,
          },
          {
            id: 4,
            subMenuLabel: "Wallet, Pay",
            url: "",
            order: 4,
            isCustomizedText: false,
          },
          {
            id: 5,
            subMenuLabel: "Siri",
            url: "",
            order: 5,
            isCustomizedText: false,
          },
        ],
      },
    ],
  },
  {
    id: 4,
    order: 4,
    label: "Watch",
    url: "",
    menuSubgroup: [
      {
        id: 0,
        subheader: "Explore Watch",
        order: 0,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Explore All Apple Watch",
            url: "",
            order: 0,
            isCustomizedText: true,
          },
          {
            id: 1,
            subMenuLabel: "Apple Watch Ultra",
            url: "",
            order: 1,
            isCustomizedText: true,
          },
          {
            id: 2,
            subMenuLabel: "Apple Watch Series 8",
            url: "",
            order: 2,
            isCustomizedText: true,
          },
          {
            id: 3,
            subMenuLabel: "Apple Watch SE",
            url: "",
            order: 3,
            isCustomizedText: true,
          },
          {
            id: 4,
            subMenuLabel: "Apple Watch Nike",
            url: "",
            order: 4,
            isCustomizedText: true,
          },
          {
            id: 5,
            subMenuLabel: "Apple Watch Hermes",
            url: "",
            order: 5,
            isCustomizedText: true,
          },
          {
            id: 6,
            subMenuLabel: "Compare Watch",
            url: "",
            order: 6,
            isCustomizedText: false,
          },
          {
            id: 7,
            subMenuLabel: "Why Apple Watch",
            url: "",
            order: 7,
            isCustomizedText: false,
          },
        ],
      },
      {
        id: 1,
        subheader: "Shop Watch",
        order: 1,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Shop Apple Watch",
            url: "",
            order: 0,
            isCustomizedText: false,
          },
          {
            id: 1,
            subMenuLabel: "Apple Watch Studio",
            url: "",
            order: 1,
            isCustomizedText: false,
          },
          {
            id: 2,
            subMenuLabel: "Apple Watch Straps",
            url: "",
            order: 2,
            isCustomizedText: false,
          },
          {
            id: 3,
            subMenuLabel: "Apple Watch Accessories",
            url: "",
            order: 3,
            isCustomizedText: false,
          },
          {
            id: 4,
            subMenuLabel: "Apple Trade In",
            url: "",
            order: 4,
            isCustomizedText: false,
          },
          {
            id: 5,
            subMenuLabel: "Financing",
            url: "",
            order: 5,
            isCustomizedText: false,
          },
        ],
      },
      {
        id: 2,
        subheader: "More from Watch",
        order: 2,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "iPhone Support",
            url: "",
            order: 0,
            isCustomizedText: false,
          },
          {
            id: 1,
            subMenuLabel: "iOS 17 Preview",
            url: "",
            order: 1,
            isCustomizedText: false,
          },
          {
            id: 2,
            subMenuLabel: "iPhone Privacy",
            url: "",
            order: 2,
            isCustomizedText: false,
          },
          {
            id: 3,
            subMenuLabel: "iCloud",
            url: "",
            order: 3,
            isCustomizedText: false,
          },
          {
            id: 4,
            subMenuLabel: "Wallet, Pay",
            url: "",
            order: 4,
            isCustomizedText: false,
          },
          {
            id: 5,
            subMenuLabel: "Siri",
            url: "",
            order: 5,
            isCustomizedText: false,
          },
        ],
      },
    ],
  },
  {
    id: 5,
    order: 5,
    label: "AirPods",
    url: "",
    menuSubgroup: [
      {
        id: 0,
        subheader: "Explore AirPods",
        order: 0,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Explore All AirPods",
            url: "",
            order: 0,
            isCustomizedText: true,
          },
          {
            id: 1,
            subMenuLabel: "AirPods Pro (2nd generation)",
            url: "",
            order: 1,
            isCustomizedText: true,
          },
          {
            id: 2,
            subMenuLabel: "AirPods (2nd generation)",
            url: "",
            order: 2,
            isCustomizedText: true,
          },
          {
            id: 3,
            subMenuLabel: "AirPods (3rd generation)",
            url: "",
            order: 3,
            isCustomizedText: true,
          },
          {
            id: 4,
            subMenuLabel: "AirPods Max",
            url: "",
            order: 4,
            isCustomizedText: true,
          },
          {
            id: 5,
            subMenuLabel: "Compare AirPods",
            url: "",
            order: 5,
            isCustomizedText: false,
          },
        ],
      },
      {
        id: 1,
        subheader: "Shop AirPods",
        order: 1,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Shop AirPods",
            url: "",
            order: 0,
            isCustomizedText: false,
          },
          {
            id: 1,
            subMenuLabel: "AirPods Accessories",
            url: "",
            order: 1,
            isCustomizedText: false,
          },
        ],
      },
      {
        id: 2,
        subheader: "More from AirPods",
        order: 2,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "AirPods Support",
            url: "",
            order: 0,
            isCustomizedText: false,
          },
          {
            id: 1,
            subMenuLabel: "Apple Music",
            url: "",
            order: 1,
            isCustomizedText: false,
          },
        ],
      },
    ],
  },
  {
    id: 6,
    order: 6,
    label: "TV & Home",
    url: "",
    menuSubgroup: [
      {
        id: 0,
        subheader: "Explore TV & Home",
        order: 0,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Explore TV & Home",
            url: "",
            order: 0,
            isCustomizedText: true,
          },
          {
            id: 1,
            subMenuLabel: "Apple TV 4K",
            url: "",
            order: 1,
            isCustomizedText: true,
          },
          {
            id: 2,
            subMenuLabel: "HomePod",
            url: "",
            order: 2,
            isCustomizedText: true,
          },
          {
            id: 3,
            subMenuLabel: "HomePod mini",
            url: "",
            order: 3,
            isCustomizedText: true,
          },
        ],
      },
      {
        id: 1,
        subheader: "Shop TV & Home",
        order: 1,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Shop Apple TV 4K",
            url: "",
            order: 0,
            isCustomizedText: false,
          },
          {
            id: 1,
            subMenuLabel: "Shop HomePod",
            url: "",
            order: 1,
            isCustomizedText: false,
          },
          {
            id: 2,
            subMenuLabel: "Shop HomePod mini",
            url: "",
            order: 2,
            isCustomizedText: false,
          },
          {
            id: 3,
            subMenuLabel: "Shop Siri Remote",
            url: "",
            order: 3,
            isCustomizedText: false,
          },
          {
            id: 4,
            subMenuLabel: "TV & Home Accessories",
            url: "",
            order: 4,
            isCustomizedText: false,
          },
        ],
      },
      {
        id: 2,
        subheader: "More from TV & Home",
        order: 2,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Apple TV Support",
            url: "",
            order: 0,
            isCustomizedText: false,
          },
          {
            id: 1,
            subMenuLabel: "HomePod Support",
            url: "",
            order: 1,
            isCustomizedText: false,
          },
          {
            id: 2,
            subMenuLabel: "Apple TV app",
            url: "",
            order: 2,
            isCustomizedText: false,
          },
          {
            id: 3,
            subMenuLabel: "Apple TV+",
            url: "",
            order: 3,
            isCustomizedText: false,
          },
          {
            id: 4,
            subMenuLabel: "Home app",
            url: "",
            order: 4,
            isCustomizedText: false,
          },
          {
            id: 5,
            subMenuLabel: "Apple Music",
            url: "",
            order: 5,
            isCustomizedText: false,
          },
          {
            id: 6,
            subMenuLabel: "Siri",
            url: "",
            order: 6,
            isCustomizedText: false,
          },
          {
            id: 7,
            subMenuLabel: "AirPlay",
            url: "",
            order: 7,
            isCustomizedText: false,
          },
        ],
      },
    ],
  },
  {
    id: 7,
    order: 7,
    label: "Entertainment",
    url: "",
    menuSubgroup: [
      {
        id: 0,
        subheader: "Explore Entertainment",
        order: 0,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Explore Entertainment",
            url: "",
            order: 0,
            isCustomizedText: true,
          },
          {
            id: 1,
            subMenuLabel: "Apple One",
            url: "",
            order: 1,
            isCustomizedText: true,
          },
          {
            id: 2,
            subMenuLabel: "Apple TV+",
            url: "",
            order: 2,
            isCustomizedText: true,
          },
          {
            id: 3,
            subMenuLabel: "Apple Music",
            url: "",
            order: 3,
            isCustomizedText: true,
          },
          {
            id: 4,
            subMenuLabel: "Apple Arcade",
            url: "",
            order: 4,
            isCustomizedText: true,
          },
          {
            id: 5,
            subMenuLabel: "Apple Podcasts",
            url: "",
            order: 5,
            isCustomizedText: true,
          },
          {
            id: 6,
            subMenuLabel: "Apple Books",
            url: "",
            order: 6,
            isCustomizedText: true,
          },
          {
            id: 7,
            subMenuLabel: "App Store",
            url: "",
            order: 7,
            isCustomizedText: true,
          },
        ],
      },
      {
        id: 1,
        subheader: "Support",
        order: 1,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Apple TV+ Support",
            url: "",
            order: 0,
            isCustomizedText: false,
          },
          {
            id: 1,
            subMenuLabel: "Apple Music Support",
            url: "",
            order: 1,
            isCustomizedText: false,
          },
        ],
      },
    ],
  },
  {
    id: 8,
    order: 8,
    label: "Accessories",
    url: "",
    menuSubgroup: [
      {
        id: 0,
        subheader: "Explore Entertainment",
        order: 0,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Explore Entertainment",
            url: "",
            order: 0,
            isCustomizedText: true,
          },
          {
            id: 1,
            subMenuLabel: "Apple One",
            url: "",
            order: 1,
            isCustomizedText: true,
          },
          {
            id: 2,
            subMenuLabel: "Apple TV+",
            url: "",
            order: 2,
            isCustomizedText: true,
          },
          {
            id: 3,
            subMenuLabel: "Apple Music",
            url: "",
            order: 3,
            isCustomizedText: true,
          },
          {
            id: 4,
            subMenuLabel: "Apple Arcade",
            url: "",
            order: 4,
            isCustomizedText: true,
          },
          {
            id: 5,
            subMenuLabel: "Apple Podcasts",
            url: "",
            order: 5,
            isCustomizedText: true,
          },
          {
            id: 6,
            subMenuLabel: "Apple Books",
            url: "",
            order: 6,
            isCustomizedText: true,
          },
          {
            id: 7,
            subMenuLabel: "App Store",
            url: "",
            order: 7,
            isCustomizedText: true,
          },
        ],
      },
      {
        id: 1,
        subheader: "Support",
        order: 1,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Apple TV+ Support",
            url: "",
            order: 0,
            isCustomizedText: false,
          },
          {
            id: 1,
            subMenuLabel: "Apple Music Support",
            url: "",
            order: 1,
            isCustomizedText: false,
          },
        ],
      },
    ],
  },
  {
    id: 9,
    order: 9,
    label: "Support",
    url: "",
    menuSubgroup: [
      {
        id: 0,
        subheader: "Explore Entertainment",
        order: 0,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Explore Entertainment",
            url: "",
            order: 0,
            isCustomizedText: true,
          },
          {
            id: 1,
            subMenuLabel: "Apple One",
            url: "",
            order: 1,
            isCustomizedText: true,
          },
          {
            id: 2,
            subMenuLabel: "Apple TV+",
            url: "",
            order: 2,
            isCustomizedText: true,
          },
          {
            id: 3,
            subMenuLabel: "Apple Music",
            url: "",
            order: 3,
            isCustomizedText: true,
          },
          {
            id: 4,
            subMenuLabel: "Apple Arcade",
            url: "",
            order: 4,
            isCustomizedText: true,
          },
          {
            id: 5,
            subMenuLabel: "Apple Podcasts",
            url: "",
            order: 5,
            isCustomizedText: true,
          },
          {
            id: 6,
            subMenuLabel: "Apple Books",
            url: "",
            order: 6,
            isCustomizedText: true,
          },
          {
            id: 7,
            subMenuLabel: "App Store",
            url: "",
            order: 7,
            isCustomizedText: true,
          },
        ],
      },
      {
        id: 1,
        subheader: "Support",
        order: 1,
        url: "",
        submenuItems: [
          {
            id: 0,
            subMenuLabel: "Apple TV+ Support",
            url: "",
            order: 0,
            isCustomizedText: false,
          },
          {
            id: 1,
            subMenuLabel: "Apple Music Support",
            url: "",
            order: 1,
            isCustomizedText: false,
          },
        ],
      },
    ],
  },
];
